pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        sh '''
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        '''
      }
    }

    stage('Lint') {
      steps {
        withCredentials([file(credentialsId: 'aiiis-ci-env', variable: 'CI_ENV_FILE')]) {
          sh '''
            set -a
            . "$CI_ENV_FILE"
            set +a
            . .venv/bin/activate
            python -m flake8 app tests --ignore=E501,E302,W293,F401
          '''
        }
      }
    }

    stage('Test') {
      steps {
        withCredentials([file(credentialsId: 'aiiis-ci-env', variable: 'CI_ENV_FILE')]) {
          sh '''
            set -a
            . "$CI_ENV_FILE"
            set +a
            . .venv/bin/activate
            python -m pytest -q
          '''
        }
      }
    }
  }
}
