pipeline {
  agent any

  environment {
    APP_NAME = 'AI Incident Investigation System'
    APP_ENV = 'ci'
    APP_HOST = '127.0.0.1'
    APP_PORT = '8000'
    POSTGRES_USER = 'aiiis'
    POSTGRES_PASSWORD = 'aiiis'
    POSTGRES_DB = 'aiiis'
    POSTGRES_HOST = '127.0.0.1'
    POSTGRES_PORT = '5432'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        sh '''
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        '''
      }
    }

    stage('Lint') {
      steps {
        sh '''
          . .venv/bin/activate
          python -m flake8 app tests --ignore=E501,E302,W293,F401
        '''
      }
    }

    stage('Test') {
      steps {
        sh '''
          . .venv/bin/activate
          python -m pytest -q
        '''
      }
    }
  }
}
