from types import SimpleNamespace

import pytest

from app.llm.base_provider import BaseLLMProvider
from app.llm.huggingface_provider import HuggingFaceProvider
from app.llm.ollama_provider import OllamaProvider
from app.llm.openai_provider import OpenAIProvider
from app.services import llm_service
from app.services.exceptions import LLMProviderError


class FakeProvider(BaseLLMProvider):
    def __init__(self) -> None:
        self.last_call: dict[str, str | None] | None = None

    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        model: str | None = None,
    ) -> str:
        self.last_call = {
            "prompt": prompt,
            "system_prompt": system_prompt,
            "model": model,
        }
        return "generated by fake provider"


def test_generate_with_local_llm_calls_provider_interface(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fake_provider = FakeProvider()
    monkeypatch.setattr(llm_service, "get_llm_provider", lambda: fake_provider)

    result = llm_service.generate_with_local_llm(
        prompt="check interface",
        system_prompt="be short",
        model="llama3.2:3b",
    )

    assert result == "generated by fake provider"
    assert fake_provider.last_call == {
        "prompt": "check interface",
        "system_prompt": "be short",
        "model": "llama3.2:3b",
    }


def test_get_llm_provider_returns_ollama_provider(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    llm_service.get_llm_provider.cache_clear()
    monkeypatch.setattr(
        llm_service,
        "get_settings",
        lambda: SimpleNamespace(llm_provider="ollama"),
    )

    provider = llm_service.get_llm_provider()

    assert isinstance(provider, OllamaProvider)
    llm_service.get_llm_provider.cache_clear()


def test_get_llm_provider_returns_huggingface_provider(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    llm_service.get_llm_provider.cache_clear()
    monkeypatch.setattr(
        llm_service,
        "get_settings",
        lambda: SimpleNamespace(llm_provider="huggingface"),
    )

    provider = llm_service.get_llm_provider()

    assert isinstance(provider, HuggingFaceProvider)
    llm_service.get_llm_provider.cache_clear()


def test_get_default_llm_model_huggingface(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        llm_service,
        "get_settings",
        lambda: SimpleNamespace(
            llm_provider="huggingface",
            ollama_model="llama3.2:3b",
            huggingface_model="google/flan-t5-base",
        ),
    )

    model = llm_service.get_default_llm_model()

    assert model == "google/flan-t5-base"


def test_get_llm_provider_returns_openai_provider(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    llm_service.get_llm_provider.cache_clear()
    llm_service.get_llm_provider_by_name.cache_clear()
    monkeypatch.setattr(
        llm_service,
        "get_settings",
        lambda: SimpleNamespace(llm_provider="openai"),
    )

    provider = llm_service.get_llm_provider()

    assert isinstance(provider, OpenAIProvider)
    llm_service.get_llm_provider.cache_clear()
    llm_service.get_llm_provider_by_name.cache_clear()


def test_get_default_llm_model_openai(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        llm_service,
        "get_settings",
        lambda: SimpleNamespace(
            llm_provider="openai",
            ollama_model="llama3.2:3b",
            huggingface_model="google/flan-t5-base",
            openai_model="gpt-4o-mini",
        ),
    )

    model = llm_service.get_default_llm_model()

    assert model == "gpt-4o-mini"


def test_generate_with_provider_calls_named_provider(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fake_provider = FakeProvider()
    monkeypatch.setattr(
        llm_service, "get_llm_provider_by_name", lambda name: fake_provider
    )

    text = llm_service.generate_with_provider(
        provider_name="openai",
        prompt="compare",
        system_prompt="brief",
        model="gpt-4o-mini",
    )

    assert text == "generated by fake provider"
    assert fake_provider.last_call == {
        "prompt": "compare",
        "system_prompt": "brief",
        "model": "gpt-4o-mini",
    }


def test_get_llm_provider_raises_for_unsupported_provider(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    llm_service.get_llm_provider.cache_clear()
    monkeypatch.setattr(
        llm_service,
        "get_settings",
        lambda: SimpleNamespace(llm_provider="unsupported"),
    )

    with pytest.raises(LLMProviderError, match="unsupported_llm_provider"):
        llm_service.get_llm_provider()

    llm_service.get_llm_provider.cache_clear()
